Add new FAQs to index.html
CORD-ai/cord-website pull request #30
Opened 2022-08-29 11:00 UTC by BalajiAI

As referenced in [this issue](https://github.com/CORD-ai/cord-website/issues/24), I've added 2 extra FAQ to index.html.
Kindly see the changes that I've made.

2022-08-29 15:44 UTC, AneeshBose commented
@BalajiAI You can also add content taking stuff from here - https://www.linkedin.com/feed/update/urn:li:activity:6939230394982486016

2022-08-29 19:28 UTC, Anindyadeep approved these changes
LGTM. But yes, you can take the additional motivations from there and also from any other website if required.

2022-08-30 05:08 UTC, BalajiAI commented
@AneeshBose @Anindyadeep Yeah, I can do it. But, There're already 8 FAQs are there in the website, so I think it's okay for now (since adding more doesn't looks good). We can discuss it about in our upcoming meeting.
What ars your thoughts?

2022-08-30 05:40 UTC, Anindyadeep commented
Yeahh that's fine.

2022-08-30 07:06 UTC, AneeshBose commented
> @AneeshBose @Anindyadeep Yeah, I can do it. But, There're already 8 FAQs are there in the website, so I think it's okay for now (since adding more doesn't looks good). We can discuss it about in our upcoming meeting. @GM-git-dotcom also mentioned that he can also help with this. What are your thoughts?

Let's keep it 8 and prioritize the most important ones.

2022-08-30 11:53 UTC, BalajiAI commented
> > @AneeshBose @Anindyadeep Yeah, I can do it. But, There're already 8 FAQs are there in the website, so I think it's okay for now (since adding more doesn't looks good). We can discuss it about in our upcoming meeting. @GM-git-dotcom also mentioned that he can also help with this. What are your thoughts?
> 
> Let's keep it 8 and prioritize the most important ones.

Yes !

2022-08-30 18:08 UTC, AneeshBose requested changes

2022-08-30 18:08 UTC, AneeshBose commented on index.html
>                  Other opportunities include, getting referrals, LoRs (in longer terms). Other perks include, getting chances to host different sessions,
@BalajiAI This is one thing which might need changing. Please incorporate and I will merge this.

2022-08-31 07:02 UTC, BalajiAI commented on index.html
>                  Other opportunities include, getting referrals, LoRs (in longer terms). Other perks include, getting chances to host different sessions,
Yeah. I've updated the answer for the faq7. Kindly see the changes.

2022-08-31 09:57 UTC, AneeshBose approved these changes
LGTM!

2022-08-31 09:58 UTC, merged