UI testing
CORD-ai/cord-website pull request #59
Opened 2024-07-02 21:03 UTC by Abinash-Anand

# Re-Design of the website

1. Redesigned the entire website aesthetic.
2. Added a new blog section.
3. Expanded the team section with new additions.
4. Introduced a screening task section.
@Anindyadeep , @Ash-29 
![image](https://github.com/CORD-ai/cord-website/assets/74396889/05cf1455-6354-464b-8938-b87556228b84)

2024-07-03 01:25 UTC, Anindyadeep commented
@Abinash-Anand looks good, can you remove the merge conflicts, Thanks

2024-07-03 02:50 UTC, Anindyadeep requested changes
Looks good, will review once more once done resolved conflicts

2024-07-05 17:40 UTC, Abinash-Anand commented
Resolved merge conflicts in index.html, teams.html, projects.html, and stylesheet.

- Kept UI testing changes in index.html
- Incorporated necessary changes in teams.html
- Merged updates in projects.html
- Updated stylesheet with latest design changes

This commit ensures that all conflicts are resolved and the UI testing changes are preserved.

2024-07-05 21:42 UTC, Anindyadeep approved these changes

2024-07-05 21:42 UTC, merged